### ISSUE TITLE
What needs to be done 

### ISSUE THREAD

**Issue by ErikBjare** [NeuroTechX/neurotech-challenge.com#1]
Set up the minimal stuff, here's how it looks so far (not great):

![image](https://user-images.githubusercontent.com/1405370/142457783-6ad08eb4-264f-4416-a9b9-3cd98c40ccfb.png)

And here is the current neurotech-challenge.com website:

![image](https://user-images.githubusercontent.com/1405370/142458367-92e58d0a-bfbb-4d6a-bfa5-618c88940a75.png)

Basically we'll need to do some edits to the theme and the `content/_index.md` to get it to look right.

# TODO

 - [x] Write README explaining basic stuff of how things work
 - [ ] Fix style
 - [ ] Fix placement of images (like logo and banner)
 - [ ] Add call-to-action buttons (register for mailinglist)
 - [ ] Copy content over
 - [ ] Add section with sponsors
 - [ ] More things not yet on the website (discussed on the call today)
   - Give overview of process for participants
 - [ ] Set up CI

**Comment by ErikBjare** [comment]
@JohnGriffiths Did some more work (still sizing/layout issues, but it's an iteration), but going to bed now. Here is the status:

![image](https://user-images.githubusercontent.com/1405370/142532078-fbb0d9fe-598a-41d2-9b82-e2f87ef867dd.png)

I think I've got the hang of hugo + the theme + the neat `tachyons` minimal CSS toolkit used by the theme, so I'm reasonably effective now.

Not sure how much time I'll have in the coming days and week, if any, but doesn't feel like that much more work to do.

**Comment by JohnGriffiths** [comment]
Awesome!
